# Generated by Django 6.0.5 on 2026-05-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10)),
                (
                    "plan_type",
                    models.CharField(choices=[("ESPP", "ESPP"), ("RSU", "RSU")], max_length=10),
                ),
                ("date_acquired", models.DateField()),
                ("sellable_qty", models.DecimalField(decimal_places=4, max_digits=10)),
                ("cost_basis", models.DecimalField(decimal_places=5, max_digits=10)),
                (
                    "tax_status",
                    models.CharField(
                        choices=[
                            ("Long Term", "Long Term"),
                            ("Short Term", "Short Term"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["date_acquired"],
            },
        ),
    ]
