# Generated by Django 6.0.5 on 2026-05-30 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sale_price_usd",
                    models.DecimalField(decimal_places=5, max_digits=10),
                ),
                ("eur_usd_rate", models.DecimalField(decimal_places=6, max_digits=10)),
                (
                    "gross_proceeds_usd",
                    models.DecimalField(decimal_places=5, max_digits=14),
                ),
                ("net_gain_usd", models.DecimalField(decimal_places=5, max_digits=14)),
                ("tax_usd", models.DecimalField(decimal_places=5, max_digits=14)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SaleLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_lot_id", models.IntegerField()),
                ("symbol", models.CharField(max_length=10)),
                ("plan_type", models.CharField(max_length=10)),
                ("date_acquired", models.DateField()),
                ("qty_sold", models.DecimalField(decimal_places=4, max_digits=10)),
                ("cost_basis", models.DecimalField(decimal_places=5, max_digits=10)),
                ("tax_status", models.CharField(max_length=20)),
                ("gain_usd", models.DecimalField(decimal_places=5, max_digits=14)),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lots",
                        to="app.sale",
                    ),
                ),
            ],
            options={
                "ordering": ["date_acquired"],
            },
        ),
    ]
