# Generated by Django 6.0.5 on 2026-07-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_sale_salelot"),
    ]

    operations = [
        migrations.AddField(
            model_name="lot",
            name="grant_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salelot",
            name="grant_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
