# Generated by Django 6.0.5 on 2026-10-06 14:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_lot_grant_date_salelot_grant_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="sale_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
