# Generated by Django 6.1.2 on 2026-10-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_sale_sale_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="order_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="salelot",
            name="original_lot_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
